# Generated by Django 4.2.16 on 2024-09-04 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('crn_id', models.AutoField(primary_key=True, serialize=False)),
                ('crn_saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crn_usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('prq_id', models.AutoField(primary_key=True, serialize=False)),
                ('prq_nombre', models.CharField(max_length=255)),
                ('prq_estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('vhc_id', models.AutoField(primary_key=True, serialize=False)),
                ('vhc_placa', models.CharField(max_length=15)),
                ('vhc_carnet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingadmin.carnet')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('ing_id', models.AutoField(primary_key=True, serialize=False)),
                ('ing_placa_vehiculo', models.CharField(max_length=15)),
                ('ing_fecha_hora', models.DateTimeField()),
                ('ing_vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingadmin.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('fac_id', models.AutoField(primary_key=True, serialize=False)),
                ('fac_placa_vehiculo', models.CharField(max_length=15)),
                ('fac_ingreso_id', models.DateTimeField()),
                ('fac_egreso_id', models.DateTimeField()),
                ('fac_precio_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fac_vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingadmin.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('egr_id', models.AutoField(primary_key=True, serialize=False)),
                ('egr_placa_vehiculo', models.CharField(max_length=15)),
                ('egr_fecha_hora', models.DateTimeField()),
                ('egr_vehiculo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingadmin.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Conjunto_celdas',
            fields=[
                ('cnj_id', models.AutoField(primary_key=True, serialize=False)),
                ('cnj_parqueadero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingadmin.parqueadero')),
            ],
        ),
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('cld_id', models.AutoField(primary_key=True, serialize=False)),
                ('cld_numero_celda', models.IntegerField()),
                ('cld_estado', models.CharField(choices=[('Ocupado', 'Ocupado'), ('Desocupado', 'Desocupado'), ('No disponible', 'No disponible')], default='Desocupado', max_length=20)),
                ('cld_conjunto_celdas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingadmin.conjunto_celdas')),
            ],
        ),
    ]
