# Generated by Django 4.2.16 on 2024-09-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingadmin', '0002_organizacion_zona_remove_vehiculo_vhc_carnet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='egr_imagen_vehiculo',
            field=models.ImageField(default=None, upload_to='imagenes_vehiculos/'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='ing_imagen_vehiculo',
            field=models.ImageField(default=None, upload_to='imagenes_vehiculos/'),
        ),
    ]
