# Generated by Django 5.1.2 on 2024-10-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingadmin', '0004_rename_cnj_parqueadero_id_conjunto_celdas_cnj_zona_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='org_logo',
        ),
    ]
