# Generated by Django 4.2.16 on 2024-11-04 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkingadmin', '0007_alter_celda_cld_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacion',
            options={'verbose_name': 'Organización', 'verbose_name_plural': 'Organizaciones'},
        ),
        migrations.AddField(
            model_name='egreso',
            name='egr_parqueadero_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingadmin.parqueadero'),
        ),
        migrations.AddField(
            model_name='factura',
            name='fac_parqueadero_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingadmin.parqueadero'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='ing_parqueadero_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parkingadmin.parqueadero'),
        ),
    ]
